# Generated by Django 2.0 on 2017-12-12 00:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_id',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.getDir),
        ),
    ]
