# Generated by Django 2.0 on 2017-12-13 16:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='img/users/profile.jpg', upload_to=main.models.getDir),
        ),
    ]
