# Generated by Django 2.0 on 2017-12-14 05:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20171213_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=main.models.getDir),
        ),
    ]
