# Generated by Django 2.0 on 2017-12-18 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_auto_20171217_1940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pin',
            unique_together={('user', 'post')},
        ),
    ]
