# Generated by Django 2.0 on 2017-12-20 21:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20171220_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='img/users/profile.jpg', upload_to=main.models.getDir),
        ),
    ]
