# Generated by Django 2.0 on 2017-12-20 21:49

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20171220_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to=main.models.getProDir),
        ),
    ]
