# Generated by Django 2.0 on 2017-12-20 21:59

from django.db import migrations, models
import main.models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20171220_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='img/users/profile.jpg', storage=main.storage.OverwriteStorage(), upload_to=main.models.getProDir),
        ),
    ]
