# Generated by Django 2.0 on 2017-12-20 22:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20171220_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='img/users/profile.jpg', upload_to=main.models.getProDir),
        ),
    ]
