# Generated by Django 2.0 on 2017-12-20 22:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20171220_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='img/users/profile.jpg', upload_to=main.models.getProDir),
        ),
    ]
