# Generated by Django 2.0 on 2017-12-21 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20171220_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prof_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='main.Post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_posts', to='main.Post'),
        ),
    ]
